### ISSUE TITLE
Cannot parse token when picture isn't present

### ISSUE THREAD

**Issue by Tommypop2** [caojen/google-oauth#1]
Hi, due to "picture" being included within the "GooglePayload" struct, the JWT validation fails when it isn't present:
> panicked at 'called `Result::unwrap()` on an `Err` value: missing field `picture` at line 1 column 567'

The google docs also state that this property doesn't necessarily need to be present:

![image](https://user-images.githubusercontent.com/71586988/236006393-815a9565-a57d-4538-a95a-4c977a4c9164.png)

I've solved this for my codebase by simply changing the "picture" member's type to Option\<String\>, rather than String. This seems to work fine for me, although I'm not sure if it's the best fix.
If this is correct, it could be best to make most of the other members Option types, as google seems to make no guarantees about most of them being present.

I'm happy to PR this in if this is the best fix.

**Comment by caojen** [comment]
Yes, thanks for your report, and i am so sorry for this bug.

Could you please create a new PR to fix this issue, which changes `picture: String -> Option<String>`?

**Comment by caojen** [comment]
Hi, this bug has been fixed. I followed https://developers.google.com/identity/openid-connect/openid-connect and make all optional fields as `Option<T>`. Now please try version `1.1.0`.

**Comment by Tommypop2** [comment]
Awesome, everything now works on my end :)

Thanks for the cool library, it's super useful
