### ISSUE TITLE
Allow multiple client IDs for token verification

### ISSUE THREAD

**Issue by bastibense** [caojen/google-oauth#13]
I'm having a bit of an issue with authentication from native apps with multiple client IDs.

Right now you can only provide one client ID for verification. But in our case the iOS and Android and Web App all have different client IDs.

Also it would be nice to have a more detailed error message (if the claims don't match - also print their values so it's easier to track down problems).

I'm not even sure if I'm getting something wrong or trying the wrong approach here.

Braindead approach for clarification:
```rust
let client = AsyncClient::new(!vec[
        "XXXXXX1111111.apps.googleusercontent.com",
        "XXXXXX222222.apps.googleusercontent.com",
    ]);
```

**Comment by caojen** [comment]
Maybe something like `AsyncClientGroup` can help? (so there would not be any breaking change.)

**Comment by caojen** [comment]
Hi, @bastibense. A new API `AsyncClient::new_with_vec` allows you to validate with multiple client ids.
The validation passes, when the `id_token` matches one of the provided client ids.

Please try version `1.7.0`.

**Comment by caojen** [comment]
Hello, @bastibense .
A new version `1.8.0` has been published, and `google_oauth::Error` is returned, which is an `enum` that may be helpful for find out what happened during verifying.

You can find the definition here:
https://github.com/caojen/google-oauth/blob/27a94ef14cb7f1349d46d57214ba822a4146fef9/src/error.rs#L11-L36
