### ISSUE TITLE
Thank you for this wonderful lib

### ISSUE THREAD

**Issue by LittleTasteOfHeaven** [caojen/google-oauth#3]
Made my work a lot easier. Thank you! :) Would you mind setting up Github sponsor?

**Comment by caojen** [comment]
I am so glad that this lib helps you.

> So sorry for my slow reply, Github didn't remind me when this project have a new issue, I will google it.

**Comment by caojen** [comment]
By the way, I searched a lot about Github sponsor, and finally found that my country/region currently is not suppported (by github). No matter how, thanks again for your appreciation.

**Comment by tausifcreates** [comment]
Hey, thanks for replying :) All the best. Ping me when you have set up a patreon/buymeacoffee.
