### ISSUE TITLE
Any hope for WASM support?

### ISSUE THREAD

**Issue by radix** [caojen/google-oauth#7]
I would love to switch to this, if it supported WASM. I currently use my own fork of the unmaintained https://github.com/wyyerd/google-signin-rs which I had to create in order to get it to work on WASM in the cloudflare workers environment. One of the issues was that the jwt crate (at least in its default configuration?) was depending on some C algorithms from ring, so I switched it to use the jwt_compact crate, which maybe you could consider for this crate. It definitely has a much worse API than the jwt crate does, unfortunately. I have to [parse the base64 RSA components and convert to num_bigint_dig::BigUInt myself](https://github.com/arpeggiorpg/arpeggiorpg/blob/4b20ea0d1ea7485bc74f9cef3cd75cf45b33cb00/forks/google-signin-rs/src/client.rs#L94-L100) and [use their confusing "StrongAlg" API to do the validation](https://github.com/arpeggiorpg/arpeggiorpg/blob/4b20ea0d1ea7485bc74f9cef3cd75cf45b33cb00/forks/google-signin-rs/src/client.rs#L131-L151).

I am not assuming you want to support this in your library, and if you want to close this ticket, please feel free. But if you do, I would happily become a user :)

**Comment by caojen** [comment]
Hi, I publish a new version `1.5.0` and create a new feature `wasm`.

I run the command `wasm-pack build --features wasm`,  and it works, and some js files are generated in folder `pkg`.

Would you mind to have a try? I am not familiar with wasm so I just follow the wasm rust book to make it "compile".

**Comment by radix** [comment]
@caojen awesome, thank you. I'll give it a try over the next three days.

I did a quick search and I think there will be a problem with the use of `std::time::Instant` -- this doesn't work on WASM. (unfortunately, many of the issues with WASM compatibility only show up at runtime 😭). There is a crate called [instant](https://github.com/sebcrozet/instant) which offers a compatibility layer that uses the `performance.now` function from javascript if targeting a WASM platform, and otherwise is a passthrough for `std::time::Instant`.

Since I have a long weekend, I'll give it a try and see what changes still need to be made to work on my WASM platform and put up a PR.

**Comment by caojen** [comment]
> @caojen awesome, thank you. I'll give it a try over the next three days.
> 
> I did a quick search and I think there will be a problem with the use of `std::time::Instant` -- this doesn't work on WASM. (unfortunately, many of the issues with WASM compatibility only show up at runtime 😭). There is a crate called [instant](https://github.com/sebcrozet/instant) which offers a compatibility layer that uses the `performance.now` function from javascript if targeting a WASM platform, and otherwise is a passthrough for `std::time::Instant`.
> 
> Since I have a long weekend, I'll give it a try and see what changes still need to be made to work on my WASM platform and put up a PR.

Yeah, if you get any problem on your runtime, feel free to share with me.

**Comment by caojen** [comment]
When `wasm` is enabled, a new `Client` (different from `AsyncClient` and `Client`(with `blocking` feature)) can be used. In this way, `std::time::Instant` should not be imported.

**Comment by radix** [comment]
@caojen Unfortunately, std::time::SystemTime::now is also not available in wasm.  I've created a pull request to fix some issues: https://github.com/caojen/google-oauth/pull/12

**Comment by caojen** [comment]
Merged.

Thanks. As you mentioned, I will drop the `wasm.client.rs` later, maybe in next few version. But for now, I just want to make everything works.

Thanks for you help again. This is my first time coming into contact with wasm.

**Comment by radix** [comment]
@caojen thanks so much! I'm glad I can now just use this crate instead of maintaining my own fork of an abandoned crate.  I've also mentioned on the Cloudflare discord that your library works w/ Rust Workers.
